package registry

// GetClineModels returns the fallback Cline model definitions.
func GetClineModels() []*ModelInfo {
	return []*ModelInfo{
		{
			ID:                  "cline/auto",
			Object:              "model",
			Created:             1732752000,
			OwnedBy:             "cline",
			Type:                "cline",
			DisplayName:         "Cline Auto",
			Description:         "Automatic model selection by Cline",
			ContextLength:       200000,
			MaxCompletionTokens: 64000,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "claude-4-sonnet",
			Object:              "model",
			Created:             1732752000,
			OwnedBy:             "cline",
			Type:                "cline",
			DisplayName:         "Claude 4 Sonnet",
			Description:         "Claude 4 Sonnet via Cline",
			ContextLength:       200000,
			MaxCompletionTokens: 64000,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "moonshotai/kimi-k2.6",
			Object:              "model",
			Created:             1732752000,
			OwnedBy:             "cline",
			Type:                "cline",
			DisplayName:         "Kimi K2.6",
			Description:         "Kimi K2.6 via Cline",
			ContextLength:       200000,
			MaxCompletionTokens: 64000,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "kwaipilot/kat-coder-pro",
			Object:              "model",
			Created:             1732752000,
			OwnedBy:             "cline",
			Type:                "cline",
			DisplayName:         "Kat Coder Pro",
			Description:         "Kat Coder Pro via Cline",
			ContextLength:       200000,
			MaxCompletionTokens: 64000,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "arcee-ai/trinity-large-preview:free",
			Object:              "model",
			Created:             1732752000,
			OwnedBy:             "cline",
			Type:                "cline",
			DisplayName:         "Trinity Large Preview",
			Description:         "Trinity Large Preview via Cline",
			ContextLength:       200000,
			MaxCompletionTokens: 64000,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
	}
}
